version: '3'
services:
  # the actual redis search db
  redis-search:
    image: redislabs/redisearch:2.0.4
    command: ['redis-server', '--loadmodule', '/usr/lib/redis/modules/redisearch.so', '--save', '900', '1', '--save', '300', '10', '--save', '60', '10000']
    volumes:
      - ./db_backup:/data
    ports:
      - "6379:6379"
  # use the following to get a redis search compatible cli
  # connected to the running redis-search db above
  redis-bash:
    image: redislabs/redisearch:2.0.4
    command: bash
    volumes:
      - ./:/usr/src/code
      - ./db_backup:/data
    links:
      - redis-search:redis
  search_api:
    image: search-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CORS_ORIGINS: '(127\.0\.0\.1|localhost|[a-z0-9-]+\.zooniverse\.org)'
      MAX_THREADS: 1
      RACK_ENV: development
      REVISION: 'test-revision'
    ports:
      - "3000:80"
    volumes:
      - ./:/app
    links:
      - redis-search:redis
