version: '3'
services:
  redis-search:
    image: redislabs/redisearch:2.0.2
    command: ['redis-server', '--loadmodule', '/usr/lib/redis/modules/redisearch.so', '--save', '900', '1', '--save', '300', '10', '--save', '60', '10000']
    ports:
      - "6379:6379"
  redis-bash:
    image: redislabs/redisearch:2.0.2
    command: bash
    volumes:
      - ./db_backup:/data
      - ./:/usr/src/code
    links:
      - redis-search:redis
  search_api:
    image: search-app:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      CORS_ORIGINS: '(127\.0\.0\.1|localhost|[a-z0-9-]+\.zooniverse\.org)'
      MAX_THREADS: 1
      RACK_ENV: development
    ports:
      - "3000:80"
    volumes:
      - ./:/app
    links:
      - redis-search:redis
